const positivitySchema = new mongoose.Schema({
    month: String,
    year: Number,
    influenzaA: Number,
    influenzaB: Number,
    strepA: Number,
    covid: Number,
    respiratoryBiofire: {
      adenovirus: Number,
      coronavirus229E: Number,
      coronavirusHKU1: Number,
      coronavirusNL63: Number,
      coronavirusOC43: Number,
      sarsCoV2: Number,
      humanMetapneumovirus: Number,
      humanRhinovirusEnterovirus: Number,
      influenzaA: Number,
      influenzaAH1: Number,
      influenzaAH3: Number,
      influenzaAH12009: Number,
      influenzaB: Number,
      parainfluenza1: Number,
      parainfluenza2: Number,
      parainfluenza3: Number,
      parainfluenza4: Number,
      respiratorySyncytialVirus: Number,
      bordetellaParapertussis: Number,
      bordetellaPertussis: Number,
      chlamydiaPneumoniae: Number,
      mycoplasmaPneumoniae: Number,
      noneDetected: Number,
    },
    giBiofire: {
      adenovirusF4041: Number,
      astrovirus: Number,
      norovirusGIGII: Number,
      rotavirusA: Number,
      sapovirus: Number,
      campylobacter: Number,
      clostridioidesDifficile: Number,
      plesiomonasShigelloides: Number,
      salmonella: Number,
      yersiniaEnterocolitica: Number,
      vibrio: Number,
      vibrioCholerae: Number,
      escherichiaColiShigella: Number,
      enteroaggregativeEColi: Number,
      enteropathogenicEColi: Number,
      enterotoxigenicEColi: Number,
      shigaLikeToxinEColi: Number,
      eColiO157: Number,
      shigellaEIEC: Number,
      cryptosporidium: Number,
      cyclosporaCayetanensis: Number,
      entamoebaHistolytica: Number,
      giardiaLamblia: Number,
      noneDetected: Number,
    },
    meningitisBiofire: {
      escherichiaColiK1: Number,
      haemophilusInfluenzae: Number,
      listeriaMonocytogenes: Number,
      neisseriaMeningitidis: Number,
      streptococcusAgalactiae: Number,
      streptococcusPneumoniae: Number,
      cytomegalovirus: Number,
      enterovirus: Number,
      herpesSimplexVirus1: Number,
      herpesSimplexVirus2: Number,
      humanHerpesvirus6: Number,
      humanParechovirus: Number,
      varicellaZosterVirus: Number,
      cryptococcus: Number,
      noneDetected: Number,
    },
    bloodCultureBiofire: {
      // Gram-negative bacteria
      acinetobacter: Number,
      bacteroidesFragilis: Number,
      enterobacterales: Number,
      enterobacterCloacae: Number,
      escherichiaColi: Number,
      klebsiellaAerogenes: Number,
      klebsiellaOxytoca: Number,
      klebsiellaPneumoniae: Number,
      proteus: Number,
      salmonella: Number,
      serratiaMarcescens: Number,
      haemophilusInfluenzae: Number,
      neisseriaMeningitidis: Number,
      pseudomonasAeruginosa: Number,
      stenotrophomonasMaltophilia: Number,
  
      // Yeast
      candidaAlbicans: Number,
      candidaAuris: Number,
      candidaGlabrata: Number,
      candidaKrusei: Number,
      candidaParapsilosis: Number,
      candidaTropicalis: Number,
      cryptococcus: Number,
  
      // Gram-positive bacteria
      enterococcusFaecalis: Number,
      enterococcusFaecium: Number,
      listeriaMonocytogenes: Number,
      staphylococcus: Number,
      staphylococcusAureus: Number,
      staphylococcusEpidermidis: Number,
      staphylococcusLugdunensis: Number,
      streptococcus: Number,
      streptococcusAgalactiae: Number,
      streptococcusPneumoniae: Number,
      streptococcusPyogenes: Number,
  
      // Antimicrobial resistance genes
      carbapenemases: {
        imp: Number,
        kpc: Number,
        oxa48Like: Number,
        ndm: Number,
        vim: Number,
      },
      colistinResistance: {
        mcr1: Number,
      },
      esbl: {
        ctxm: Number,
      },
      methicillinResistance: {
        mecA_C: Number,
        mecA_C_MREJ: Number,
      },
      vancomycinResistance: {
        vanA_B: Number,
      },
      noneDetected: Number,
    },
  });
  
  const PositivityRate = mongoose.model('PositivityRate', positivitySchema);
  